version: '3.3'
services:
  ora2pg:
    container_name: ora2pg
    image: georgmoser/ora2pg:21.1
    environment:
      OUTPUT_LOCATION: "/output/"
      CONFIG_LOCATION: "/config/ora2pg.conf"
#      ORA_HOST: "DBI:Oracle:host=${host};sid=${instancename};port=1521;database=${dbname}"
#      ORA_USER: "${useroracle}"
#      ORA_PWD: "${pwd_useroracle}"      
    volumes:
      - ${PWD}/output:/output
      - ${PWD}/config:/config

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${ipvpn}/24 #avoid clash with VPN
