version: "3"

services:
  db_mysql:
    image: mysql:5.7
    container_name: "mysql57"
    environment:
      - MYSQL_DATABASE=${db mysql}
      - MYSQL_USER=${usr mysql}
      - MYSQL_PASSWORD=${pwd mysql}
      - MYSQL_ROOT_PASSWORD=${pwd user root}
    volumes:
      - ${PWD}/docker/db_mysql/data/mysql:/var/lib/mysql"
    ports:
      - 3306:3306
