version: "3"

services:
  db_mysql:
    image: mysql:5.7
    container_name: "mysql"
    environment:
      - MYSQL_DATABASE=db_mysql_local
      - MYSQL_USER=usr_mysql_local
      - MYSQL_PASSWORD=mysql_local
      - MYSQL_ROOT_PASSWORD=Ur45jhP0!
    volumes:
      - "$HOME/docker/db_mysql/data/mysql:/var/lib/mysql"
    ports:
      - 3306:3306
