version: "3"

services:
  db_pgsql:
    image: postgres:11.2-alpine
    container_name: "postgreSQL"
    environment:
      - POSTGRES_DB=${db pgsql}
      - POSTGRES_USER=${usr pgsql}
      - POSTGRES_PASSWORD=${pwd usr pgsql}
      - TZ=GMT
    volumes:
      - ${PWD}/docker/db_pgsql/data/postgres:/var/lib/postgresql/data"
    ports:
      - 6543:5432

