version: '3.4'

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql_server
    environment:
      - SA_PASSWORD=${pwd usr sa}
      - ACCEPT_EULA=Y
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-P$pwdsa", "-Q", "select 1"]
      interval: 1s
      retries: 20
    volumes:
      - ./sql-scripts:/scripts
    ports:
      - "1435:1433"
